---
apiVersion: v1
kind: Namespace
metadata:
  name: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-service-account
  namespace: admin
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-service-account-token
  namespace: admin
  annotations:
    kubernetes.io/service-account.name: admin-service-account
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-service-account-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-service-account
  namespace: admin